---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos:8
    image: docker.io/pycontribs/centos:8
    pre_build_image: true
  - name: ubuntu
    image: docker.io/pycontribs/ubuntu
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
